# You can remove the "version: '3.8'" line if Compose complains it is obsolete:
# version: "3.8"

services:
  rstudio:
    container_name: rstudio
    build:
      context: .
      dockerfile: Dockerfile
    image: rstudio-genomics
    ports:
      - "8787:8787"
    volumes:
      - ./data:/home/rstudio/data
    environment:
      - PASSWORD=rstudio   # Or set a safer password for production
